Implement long polling on the job and job_step GET requests
openflighthpc/flight-scheduler-controller pull request #31
Opened 2020-11-23 13:35 UTC by WilliamMcCumstie

Three new features have been implemented:

1. Long polling of a `job` to see if it can transition into the `RUNNING` state. Jobs which can preform the transition are `runnable` otherwise false.
2. Long polling of a `job_step` until each `node` has reported it being `submitted`, and
3. Serialize the base environment so it can be used by the `alloc` command

I've also reordered the `app.rb` file as it was getting a bit unwieldy. Most of the detail documentation has been moved onto the `serializers` which they represent. Also the `job_step` routes have been re-positioned after the `job` as this is the order used everywhere else.

2020-11-25 17:41 UTC, benarmston commented
@WilliamMcCumstie can you rebase this on the latest `master` please?

2020-11-26 12:20 UTC, benarmston commented
@WilliamMcCumstie I'd forgotten I'd asked you to rebase this `master`.  I've just noticed the comment above.

Anyway, I've rebased this on `master`.  I've moved the job step block in `app.rb` back to its original position as that was the easiest way to merge the changes.  It also means that the job step block and the job block are in alphabetical order.  I'm not sure if alphabetical order is a better consistency than always having Job/job before JobStep/job_step.  But it was easiest to resolve the conflict.

2020-11-26 13:49 UTC, benarmston requested changes
This is looking pretty good.  I've got a couple of requests but once they are dealt with I think this is good to go.

2020-11-26 13:49 UTC, benarmston commented on app/models/job.rb
> +  end
I'm going to call YAGNI on this.  Checking if the job is `pending?` is the better/clearer option.

Asking if the job is `runnable?` results in me wondering if `ARRAY_JOB`s are runnable.  They don't actually get ran, instead they generate an `ARRAY_TASK` which gets ran.  Does this mean that they are runnable or not runnable.  I'm not sure.

As the `alloc` command doesn't support creating array jobs, we're not going to end up polling against one.  But the method is in the `Job` class and still seems odd.

If/when we transition to a state machine to manage a job's state, we will be firing events and checking if the object can respond to that event, e.g., `can_start?`.  Or checking if the transition is possible `state_paths.to_states.include?('RUNNING')`.  Either way, we'll need to remove this method at that point.

2020-11-26 13:49 UTC, benarmston commented on lib/flight_scheduler/submission/job_step.rb
> +      @job_step.submitted = true
This doesn't look like a good idea.  If a job step fails to report back its port for some reason, `t` will never complete and we'll never exit the `call` method.  If a job step simply takes an unexpectedly long time to report back, we could end up with the `run` command timing out its request to start the job.

A better option would be to add a `submitted?` (or perhaps `running?` or `ready?`) method `JobStep` which checks if all of its executions are in the `RUNNING` state.  (`EventProcessor#job_step_started` needs fixing to set the correct state).

2020-11-26 14:35 UTC, WilliamMcCumstie commented on app/models/job.rb
> +  end
Okay I have removed the method here:
https://github.com/openflighthpc/flight-scheduler-controller/pull/31/commits/852aa86cebf8fcdfea21c1c321876b2e968d8897

The concept of "runnability" still exists in the API to control the long polling interaction in `alloc`.

2020-11-26 14:48 UTC, WilliamMcCumstie commented on lib/flight_scheduler/submission/job_step.rb
> +      @job_step.submitted = true
I have removed the `async` wait from the `Submission` and replaced with a `submitted?` flag on `JobStep`:
https://github.com/openflighthpc/flight-scheduler-controller/pull/31/commits/240c7fda7dd311fd6fbf0c375706389a581ad92d

In reference to the timeout issue, this change is unrelated to it. The `client` can't really timeout as it  blocked by its long polling loop. However the `daemons` can still timeout if a single node takes a particularly long.

2020-11-30 13:02 UTC, merged